name: Experiments

on:
  pull_request_target:
    types: [opened, edited]

jobs:
  experiment_one:
    runs-on: ubuntu-latest
    steps:
      - name: foo
        run: |
          echo "::warning title=Missing ticket ID::Your PR description is missing the ticket ID"
          echo "You did not provide a ticket ID"
          exit 1
        if: contains(github.event.pull_request.body, '- http://ticket.example.org/ABCD-1234')
