name: Experiments

on:
  # pull_request:
  pull_request_target:
    types:
      - opened
      - edited

jobs:
  experiment_one:
    runs-on: ubuntu-latest
    steps:
      - name: foo
        run: |
          if echo "${{ inputs.pull_request.pull_request.body }}" | grep -q 'http://ticket.example.org/ABCD-1234'; then
              echo "::warning title=Missing ticket ID::Your PR description is missing the ticket ID"
              exit 1
          fi
